apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scylla
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scylla
    spec:
      containers:
        - name: scylla-container
          image: scylla:latest
          ports:
            - containerPort: 9042
          env:
            - name: SCYLLA_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: SCYLLA_RPC_ADDRESS
              value: 0.0.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: scylla-service
  labels:
    app.kubernetes.io/name: scylla
spec:
  type: NodePort
  ports:
    - name: scy
      port: 9042
      nodePort: 30500
      targetPort: 9042
      protocol: TCP
  selector:
    app.kubernetes.io/name: scylla
