version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - broker

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

#  db:
#    image: cassandra:latest
#    environment:
#      - CASSANDRA_USER=cassandra
#      - CASSANDRA_PASSWORD=123456
#    ports:
#      - "9042:9042"

#  db:
#    image: scylladb/scylla
#    ports:
#      - "9042:9042"
#    volumes:
#      - ./data:/var/lib/scylla
#    environment:
#      - SCYLLA_LISTEN_ADDRESS=0.0.0.0
#      - SCYLLA_RPC_ADDRESS=0.0.0.0

  redis-yes:
    image: redis:latest # You can specify a specific Redis version if needed
    container_name: redis-yes
    ports:
      - "6379:6379"

  broker:
    build: .
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 2096M
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      - db
      - redis-yes

#  jaeger:
#    container_name: jaeger
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686"
#      - "14269:14269"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  grafana: