global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:

rule_files:

scrape_configs:
  - job_name: broker
    metrics_path:  /metrics
    static_configs:
      - targets: ["broker:9091"]

